//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.CrazyTruck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga
    {
        public int id { get; set; }
        public int idGandola { get; set; }
        public int idFlete { get; set; }
        public string descripcion { get; set; }
        public decimal peso { get; set; }
    
        public virtual Flete Flete { get; set; }
        public virtual Gandola Gandola { get; set; }
    }
}
