//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleo.CrazyTruck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga
    {
        public int id { get; set; }
        public int idGandola { get; set; }
        public int idFlete { get; set; }
        public string descripcion { get; set; }
        public decimal peso { get; set; }
    
        public virtual Flete Flete { get; set; }
        public virtual Gandola Gandola { get; set; }
    }
}
